cine_search_tdcp_cinema:
    resource: "@CineSearchTdcpBundle/Resources/config/routing/cinema.yml"
    prefix:   /cinema

index:
    path:     /
    defaults: { _controller: CineSearchTdcpBundle:Accueil:index }

geoloc:
    path:     /geoloc/
    defaults: { _controller: CineSearchTdcpBundle:Geoloc:geoloc }


